### ISSUE TITLE
How to view "output" of BBB running on separate node? 

### ISSUE THREAD

**Issue by mbellabah** [RIAPS/riaps-apps#24]
Hey team, 

My .depl files includes deployments on three BeagleBone Blacks, similar to the DistributedEstimatorGPIO example. Note that I succesffuly see the nodes when I run `riaps_ctrl` on the VM; however, each of these nodes include several `logger.info()` found within the python class definitions, e.g. `self.logger.info(f"{self.type}: PID {self.pid} - request on_query(): {request}")` How can I see that information in a terminal within my VM? 

Thanks!

**Comment by MMetelko** [comment]
Information on logging can be found at https://riaps.github.io/tutorials/logging.html.  See the **Default Logging** section.

**Comment by mbellabah** [comment]
Thanks!
